### ISSUE TITLE
Hantek seems semi-bricked after bitstream update

### ISSUE THREAD

**Issue by etodanik** [andy9a9/fx2eeprom#2]
I updated my Hantek from 0x4302 (which I can not find online) to a 0x4304 (Also tried 0x4303 with same results).

Both Windows and OSX recognize the device as `04b5:4032 ROHM Co., Ltd. LA-4032` (which seems correct). It even shows in the list in PulseView. However, it is not useable. 
<img width="405" alt="screen shot 2019-01-15 at 0 58 12" src="https://user-images.githubusercontent.com/1970424/51147054-8728c080-1861-11e9-94f3-ac4b0faba290.png">

<img width="328" alt="screen shot 2019-01-15 at 0 57 40" src="https://user-images.githubusercontent.com/1970424/51147045-82640c80-1861-11e9-910d-7a803455231f.png">

<img width="359" alt="screen shot 2019-01-15 at 0 57 48" src="https://user-images.githubusercontent.com/1970424/51146898-ed611380-1860-11e9-91b7-781441617724.png">

I had a similar result with this tool:
https://github.com/flowswitch/ht4032l-python/issues/1

@andy9a9 would you have any similar experience / ideas as to what could have happened to my Hantek?

**Comment by andy9a9** [comment]
Could you please provide the DEBUG log from pulseview/sigrok-cli?

- $ sigrok-cli -l 5 -d hantek-4032l --show > sigrok-cli.log 2>&1
- $ pulseview -l 5 &
  - Open settings(gear with wrench) > Logging > Save to File

From quick point of view, seems to be, that you have written the content into unsupported FLASH. 
Do you have a backup of previous FPGA content?

**Comment by andy9a9** [comment]
Hi @israelidanny

Is it still relevant?

**Comment by etodanik** [comment]
@andy9a9 I don't have that Hantek model around anymore. It seems that you're right regarding an unsupported flash.
